### ISSUE TITLE
Vertical scroll hangs on iPad

### ISSUE THREAD

**Issue by verloox** [scottjehl/picturefill#544]
Hi there,
I've been debugging a hang on iPad on some of our sites, for example [this one](http://www.moncler.yooxbox.com/it/uomo/giacche-giubbotti), and I found out that the hang occurs on the second vertical scroll in each direction.
This may sound strange but this is because Mobile Safari has the URL bar that shrinks when scrolling down, and expands when scrolling up, generating a "resize" event on the page. This resize event causes lots of calls to the `getWidthFromLength` function, which hangs the iPad for a while (the time depends on the iPad model's CPU).
The solution I suggest is to store the viewport at picturefill initialization, then check if the viewport width has changed after resize, and call the resize event only if width has change.
Could it work for you?

**Comment by Wilto** [comment]
Thanks for the issue report, @verloox! What version of Picturefill is this? We made some changes to the resize debouncing recently—would you mind re-testing with the latest version of Picturefill 2 in master?For extra credit, it would be hugely helpful if you could test the Picturefill 3.0 beta.

**Comment by aFarkas** [comment]
Yeah, a check with pf 3.0 beta would be awsome.

**Comment by verloox** [comment]
Thanks for the quick reply. I'll let you know.

**Comment by verloox** [comment]
Ok, the check was completed and the result is: 

* version 2.3.1 still has the problem on vertical scroll on iPad
* version 3.0.0 beta solves the problem

Anyway, we're not confident in releasing a beta version on our production environment. What solution do you suggest? Is the solution I proposed a good solution? Alternatively, how much time is missing before version 3.0.0 will reach the stable channel?

Thank you

**Comment by mike-engel** [comment]
@verloox 3.0 is actually, as far as we're concerned, pretty stable. It's a complete rewrite of picturefill that fixes many long-standing issues, which is why it's in beta. It's been in alpha for a month-ish, and in beta for about a week without any issues (or at least any that came in are now fixed). In fact, the picturefill demo site is using 3.0 at the moment. If you're still concerned about the beta label, we'll probably keep it on for at least another week or two.

Thanks!

**Comment by monsdroid** [comment]
Hi,
we have 2 picture arts and ~40 img srcset tags on a page.  `3.0.0 beta 1` scrolls smoother than version 2.3.1 but doesn't solve the problem of stottering during scrolling on iphones/pads. After an initially short hanging period it runs mostly smooth until i change the scroll direction  (top->down to down->up and vice versa).
A very short debugging showed, that in our case, the most responsnes get's lost in `getWidthFromLength` (iPhone 4s). It gets fired everytime i scroll. not so sure why.

**Comment by aFarkas** [comment]
@monsdroid 
I just changed the code to deal with this problem. Basically it does the same thing that already was suggested by @verloox.

Could you please test whether this helps with your problem.

**Comment by aFarkas** [comment]
@monsdroid  

I tried to fix this problem in the ["ios_scrollbug-544" branch](https://github.com/scottjehl/picturefill/tree/ios_scrollbug-544/dist). It would be great if you could confirm that the code changes in this branch are fixing your problem.

**Comment by monsdroid** [comment]
@aFarkas it works really smooth now. thanks a lot!

**Comment by verlok** [comment]
It seems fixed now. Thank you.
Here's a [comparison between picturefill 2, picturefill 3 beta, and picturefill 3 beta with the fix](http://verlok.github.io/img_srcset_lazyload/)
The examples above also implements the *lazy load* technique.

**Comment by verlok** [comment]
We really want picturefill 3 to be released... how much time you think it will still take?
Thank you for all your work!
